apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  generateName: cel-run-
spec:
  ref:
    apiVersion: cel.example.dev/v0
    kind: CEL
  params:
  - name: expression
    value: "{'blue': '0x000080', 'red': '0xFF0000'}['red'] == '0xFF0000'"
